// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmckfurhcufyhcampant.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tY2tmdXJoY3VmeWhjYW1wYW50Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4Nzc2NzcsImV4cCI6MjA2NjQ1MzY3N30.TKodacjP7Uig9GxnydAJzRcBKUpMAMR8UfWe1HsVgjM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);